---
- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: brew_installed

- name: Install Homebrew
  when: not brew_installed.stat.exists
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    NONINTERACTIVE: "1"

- name: Add Homebrew taps
  become: yes
  become_user: "{{ username }}"
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_facts['env']['PATH'] }}"
  loop:
    - jesseduffield/lazydocker

- name: Install Homebrew formulae
  become: yes
  become_user: "{{ username }}"
  community.general.homebrew:
    name: "{{ brew_packages }}"
    state: present
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_facts['env']['PATH'] }}"

- name: Install Homebrew casks
  become: yes
  become_user: "{{ username }}"
  community.general.homebrew_cask:
    name: "{{ brew_casks }}"
    state: present
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_facts['env']['PATH'] }}"

- name: Register yazi piper plugin
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: /home/linuxbrew/.linuxbrew/bin/ya pkg add yazi-rs/plugins:piper
  register: yazi_plugin_result
  changed_when: "'already exists' not in yazi_plugin_result.stderr"
  failed_when: "yazi_plugin_result.rc != 0 and 'already exists' not in yazi_plugin_result.stderr"

- name: Install yazi plugins
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: /home/linuxbrew/.linuxbrew/bin/ya pkg install
  changed_when: true
