---
- name: Apply macOS defaults
  ansible.builtin.command:
    argv:
      - sh
      - "{{ playbook_dir }}/files/macos/defaults.sh"
  register: macos_defaults
  changed_when: macos_defaults.stdout == "changed"
  tags:
    - macos
    - macos-defaults
