---
- name: Default NVIDIA GPU fact to false
  ansible.builtin.set_fact:
    has_nvidia_gpu: false

- name: Detect NVIDIA PCI devices
  ansible.builtin.shell:
    cmd: "grep -l '^0x10de$' /sys/bus/pci/devices/*/vendor"
  register: nvidia_pci_vendor_grep
  check_mode: false
  changed_when: false
  failed_when: false

- name: Set NVIDIA GPU fact
  ansible.builtin.set_fact:
    has_nvidia_gpu: "{{ nvidia_pci_vendor_grep.rc == 0 }}"
