---
# fnm (Fast Node Manager)
- name: Check if fnm is installed
  ansible.builtin.stat:
    path: "{{ user_home }}/.local/share/fnm/fnm"
  register: fnm_installed

- name: Install fnm
  when: not fnm_installed.stat.exists
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.shell:
    cmd: curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell

- name: Install default Node version via fnm
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ user_home }}/.local/share/fnm/fnm install --lts"

- name: Get latest installed fnm Node version
  ansible.builtin.shell:
    cmd: "find {{ user_home }}/.local/share/fnm/node-versions -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort -V | tail -n1"
  register: fnm_default_version
  changed_when: false

- name: Set default Node version via fnm
  when: fnm_default_version.stdout != ""
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "{{ user_home }}/.local/share/fnm/fnm default {{ fnm_default_version.stdout }}"

- name: Install npm global packages
  become: yes
  become_user: "{{ username }}"
  community.general.npm:
    name: "{{ item }}"
    executable: "{{ user_home }}/.local/share/fnm/aliases/default/bin/npm"
    global: true
    state: present
  environment:
    PATH: "{{ user_home }}/.local/share/fnm/aliases/default/bin:{{ ansible_facts['env']['PATH'] }}"
  loop: "{{ npm_global_packages }}"

# uv (Python package manager)
- name: Check if uv is installed
  ansible.builtin.stat:
    path: "{{ user_home }}/.local/bin/uv"
  register: uv_installed

- name: Install uv
  when: not uv_installed.stat.exists
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.shell:
    cmd: curl -LsSf https://astral.sh/uv/install.sh | sh

# bun
- name: Check if bun is installed
  ansible.builtin.stat:
    path: "{{ user_home }}/.bun/bin/bun"
  register: bun_installed

- name: Install bun
  when: not bun_installed.stat.exists
  become: yes
  become_user: "{{ username }}"
  ansible.builtin.shell:
    cmd: curl -fsSL https://bun.sh/install | bash
