---
security_ssh_port: 666
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
security_ssh_allowed_users:
  - "{{ username }}"
security_autoupdate_enabled: true
security_autoupdate_reboot: "false"
security_fail2ban_enabled: true
# Antigen / ZSH vars
antigen_install_oh_my_zsh: yes
ansible_ssh_user: "{{ lookup('env', 'USER') }}"

username: "{{ lookup('env', 'USER') }}"
user_home: "{{ lookup('env', 'HOME') }}"
repo_root: "{{ user_home }}/repo/dotfiles-rbw"
legacy_repo_root: "{{ user_home }}/repo/dotfiles"
zshrc_home: "{{ user_home }}/.zshrc"
zshrc_repo: "{{ repo_root }}/home/.zshrc"
home_repo: "{{ repo_root }}/home"

enable_antigen_role: true
enable_git_role: true
enable_security_role: true
enable_miniconda_role: false
enable_i3: false
