#!/usr/bin/env bash

killall polybar
sleep 2 &

# Polybar
# nVidia only
polybar top -q &
polybar bottom -q &

# iGPU only
#polybar botIPS -q &
#polybar botDP2 -q &
#polybar topIPS -q &
#polybar topDP2 -q &

# nitrogen
nitrogen --restore &

#nohup mopidy &
#nohup deluged &
#nohup deluge-web &

