#!/usr/bin/env bash

# killall polybar
# sleep 2 &

# Polybar
# nVidia only
# for m in $(polybar --list-monitors | cut -d":" -f1); do
#     for bar in top bottom; do
#     MONITOR=$m polybar --reload $bar &
#     done
# done
# iGPU only
#polybar botIPS -q &
#polybar botDP2 -q &
#polybar topIPS -q &
#polybar topDP2 -q &

# nitrogen
nitrogen --restore &
nm-applet &

#nohup mopidy &
#nohup deluged &
#nohup deluge-web &
