---
  - name: Upgrade all packages
    become: yes
    community.general.pacman:
      update_cache: yes
      upgrade: yes

  - name: Ensure arch specific packages are installed
    become: yes
    ansible.builtin.package:
      name: "{{ arch_packages }}"
      state: present

  - name: Create the `aur_builder` user
    become: yes
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: Allow the `aur_builder` user to run `sudo pacman` without a password
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  - name: Install aur packages using makepkg if it isn't installed already
    kewlfft.aur.aur:
      name: "{{ aur_packages }}"
      use: makepkg
      state: present
    become: yes
    become_user: aur_builder

  - name: Ensure docker users are added to the docker group.
    become: yes
    user:
      name: rbw
      groups: docker
      append: true

  - name: Symlink alacritty config folder
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/home/config/alacritty
      dest: $HOME/.config/alacritty
      state: link
      force: yes

  - name: Symlink gtk-3.0 config
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/home/config/gtk-3.0
      dest: $HOME/.config/gtk-3.0
      state: link
      force: yes

  - name: Symlink gtkrc for gt2k
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/home/.gtkrc-2.0
      dest: $HOME/.gtkrc-2.0
      state: link
      force: yes