---  
  - name: Install packages
    become: yes
    ansible.builtin.package:
      name: "{{ i3_packages }}"
      state: present

  - name: Remove i3 config folder if exists
    ansible.builtin.file:
      path: "{{ user_home }}/.config/i3"
      state: absent


  - name: Symlink i3 config folder
    ansible.builtin.file:
      src: "{{ repo_root }}/home/config/i3"
      dest: "{{ user_home }}/.config/i3"
      state: link
      force: yes
  
  - name: Symlink polybar config folder
    ansible.builtin.file:
      src: "{{ repo_root }}/home/config/polybar"
      dest: "{{ user_home }}/.config/polybar"
      state: link
      force: yes

  - name: Symlink Dunst config folder
    ansible.builtin.file:
      src: "{{ repo_root }}/home/config/dunst"
      dest: "{{ user_home }}/.config/dunst"
      state: link
      force: yes

  - name: Symlink wallpapers folder
    ansible.builtin.file:
      src: "{{ repo_root }}/wallpapers"
      dest: "{{ user_home }}/.config/wallpapers"
      state: link
      force: yes

  - name: Symlink picom
    ansible.builtin.file:
      src: "{{ repo_root }}/home/config/picom"
      dest: "{{ user_home }}/.config/picom"
      state: link
      force: yes

  - name: Clone polybar-scripts repo
    ansible.builtin.git:
      repo: https://github.com/polybar/polybar-scripts
      version: master
      dest: "{{ user_home }}/repo/polybar-scripts"
      # single_branch: yes
      # update: yes

  - name: Symlink polybar-scripts inside polybar-config
    ansible.builtin.file:
      src: "{{ user_home }}/repo/polybar-scripts"
      dest: "{{ user_home }}/.config/polybar-scripts"
      state: link
      force: yes

  - name: Symlink rofi config
    ansible.builtin.file:
      src: "{{ repo_root }}/home/config/rofi"
      dest: "{{ user_home }}/.config/rofi"
      state: link
      force: yes