---  
  - name: Install packages
    become: yes
    ansible.builtin.package:
      name: "{{ i3_packages }}"
      state: present

  - name: Remove i3 config folder if exists
    ansible.builtin.file:
      path: $HOME/.config/i3
      state: absent


  - name: Symlink i3 config folder
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/home/config/i3
      dest: $HOME/.config/i3
      state: link
      force: yes
  
  - name: Symlink polybar config folder
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/home/config/polybar
      dest: $HOME/.config/polybar
      state: link
      force: yes

  - name: Symlink Dunst config folder
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/home/config/dunst
      dest: $HOME/.config/dunst
      state: link
      force: yes

  - name: Symlink wallpapers folder
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/wallpapers
      dest: $HOME/.config/wallpapers
      state: link
      force: yes
