---
  - name: Install base packages
    become: yes
    ansible.builtin.package:
      name: "{{ base_packages }}"
      state: present
    tags:
      - packages
  
  - name: Copy SSH public keys from Github
    ansible.posix.authorized_key:
      user: rbw
      state: present
      key: https://github.com/rbozydar.keys

  - name: Create repo folder
    ansible.builtin.file:
      state: directory
      dest: $HOME/repo
  
  - name: Clone & pull dotfiles
    ansible.builtin.git:
      repo: git@github.com:RBozydar/dotfiles-rbw.git
      version: main
      dest: $HOME/repo/dotfiles
      single_branch: yes
      update: yes
      accept_hostkey: yes

# remove existing file? compare maybe and only then
  - name: Register current state of .zshrc
    stat:
      path: "{{ zshrc_home }}"
      checksum: sha1
      get_checksum: yes
    register: zshrc_home_checksum

  - name: Register .zshrc in repository
    stat:
      path: "{{ zshrc_repo }}"
      checksum: sha1
      get_checksum: yes
    register: zshrc_repo_checksum

  - name: Symlink .zshrc
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/home/.zshrc
      dest: $HOME/.zshrc
      state: link
      force: yes
    when: zshrc_repo_checksum != zshrc_home_checksum

  - name: Symlink .zsh_aliases
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/home/.zsh_aliases
      dest: $HOME/.zsh_aliases
      state: link
      force: yes
  
  - name: Symlink .zsh_exports
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/home/.zsh_exports
      dest: $HOME/.zsh_exports
      state: link
      force: yes

  - name: Symlink gitconfig
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/home/.gitconfig
      dest: $HOME/.gitconfig
      state: link
      force: yes

  - name: Symlink git_ingore global
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/home/.gitignore_global
      dest: $HOME/.gitignore_global
      state: link
      force: yes

  - name: Symlink conda config folder
    ansible.builtin.file:
      src: $HOME/repo/dotfiles/home/.config/conda
      dest: $HOME/.config/conda
      state: link
      force: yes