---
  - name: Upgrade all packages
    become: yes
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: true

  - name: Ensure Universe repository is enabled
    become: yes
    ansible.builtin.apt_repository:
      repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_facts['distribution_release'] }} universe"
      state: present
    tags:
      - packages

  - name: Install Ubuntu packages
    become: yes
    ansible.builtin.apt:
      name: "{{ ubuntu_packages }}"
      state: present
    tags:
      - packages

  - name: Codex sandbox prerequisites
    ansible.builtin.include_tasks: tasks/codex-sandbox.yml
    tags:
      - codex-sandbox

  - name: GH CLI
    ansible.builtin.include_tasks: tasks/gh-cli.yml
    tags:
      - gh-cli

  - name: Glow
    ansible.builtin.include_tasks: tasks/glow.yml
    tags:
      - glow

  - name: NVIDIA CUDA
    ansible.builtin.include_tasks: tasks/nvidia-cuda.yml
    when: has_nvidia_gpu | default(false) | bool
    tags:
      - nvidia

  - name: Homebrew
    ansible.builtin.include_tasks: tasks/homebrew.yml
    tags:
      - homebrew
