- hosts: ubuntu
  vars_files:
    - vars/main.yml
    - vars/packages.yml
  roles:
    - role: geerlingguy.docker
      become: yes
      docker_users:
        - rbw

  tasks:
  - name: Update apt cache
    become: yes
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 3600

  - name: Upgrade all packages
    become: yes
    ansible.builtin.apt:
      upgrade: dist

  - name: Install ubuntu packages
    become: yes
    ansible.builtin.apt:
      name: "{{ ubuntu_packages }}"
      state: present
    tags:
      - packages

  - name: GH CLI
    ansible.builtin.include_tasks: tasks/gh-cli.yml
    tags:
      - gh-cli

  - name: Glow
    ansible.builtin.include_tasks: tasks/glow.yml
    tags:
      - glow

  - name: NVIDIA CUDA
    ansible.builtin.include_tasks: tasks/nvidia-cuda.yml
    tags:
      - nvidia