Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/ubuntu-26.04"
  config.vm.hostname = "dotfiles-test"

  config.vm.provider :libvirt do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.synced_folder "../home", "/home/vagrant/repo/dotfiles/home", type: "rsync"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ubuntu.yml"
    ansible.extra_vars = {
      username: "vagrant",
      home_repo: "/home/vagrant/repo/dotfiles/home",
      ansible_ssh_user: "vagrant"
    }
    ansible.groups = {
      "ubuntu" => ["default"]
    }
    ansible.galaxy_role_file = "requirements.yml"
    ansible.galaxy_command = "ansible-galaxy install -r %{role_file}"
    ansible.compatibility_mode = "2.0"
    # ansible.skip_tags = "nvidia"
  end
end
